services:
  - type: web
    name: cg-news-express
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "CG News Express"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:2KGmjKQzfxrmNMAVssWjOohIh6Nz13Tq+TSIr3Bkivo="
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: cookie
